theme: jekyll-theme-minimal
title: Ólavur Mortensen
description: Population genetics, bioinformatics, machine learning, Python || [Publications](publications) || [Projects](projects) || [Teaching](teaching)
